# Generated by Django 4.0.4 on 2022-04-12 12:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('quizz', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='categorie',
        ),
        migrations.RemoveField(
            model_name='question',
            name='createur',
        ),
        migrations.CreateModel(
            name='Quizz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=200)),
                ('categorie', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizz.categorie')),
                ('createur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='quizz',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='quizz.quizz'),
        ),
    ]
